// client/src/lib/components/Project.svelte
<script lang="ts">
    import type Project from "$lib/models/Project";
    import Link from "./Link.svelte";

    export let project: Project;
</script>

<div
    class="text-white grid grid-cols-4 ml-[25px] sm:ml-[50px] mr-0 font-[SFUI] mt-[25px]"
>
    <div>
        <img
            alt={project.name}
            src={project.imagePath}
            class="rounded-[100%]"
            width={150}
            height={150}
        />
    </div>
    <div class="pl-[15px] w-[250%]">
        <span class="italic text-[22px] font-bold">
            {project.name} ({project.startYear}-{project.endYear ?? "Present"})
        </span>
        <div class="mt-[10px]" />
        <span class="w-[250%] text-[18px]">
            {project.description}
        </span>
        <br />
        {#if project.website}
            <Link
                link={{
                    name: "View Website...",
                    link: project.website,
                }}
            />
            &nbsp;
        {/if}
        {#if project.sourceCode}
            <Link
                link={{
                    name: "Check the madness behind this...",
                    link: project.sourceCode,
                }}
            />
        {/if}
    </div>
</div>

// components/Project/index.tsx
import * as React from "react";
import Image from "next/image";
import Link from "next/link";

interface WSProps {
  name: string;
  link: string;
}

const Website = ({ name, link }: WSProps): React.ReactElement => {
  return (
    <div className="font-[SFUI] text-[16px] text-white inline-block underline">
      <Link href={link}>
        <a target="_blank">{name}</a>
      </Link>
    </div>
  );
};

interface Props {
  name: string;
  startYear: string;
  endYear?: string;
  description: string;
  website?: string;
  sourceCode?: string;
  image: string;
}

const Project = ({
  name,
  startYear,
  endYear,
  description,
  website,
  sourceCode,
  image,
}: Props): React.ReactElement => {
  return (
    <div className="text-white grid grid-cols-4 md:pl-[50px] m-[10px] font-[SFUI] pt-[20px]">
      <div>
        <Image
          src={image}
          width={150}
          height={150}
          className="rounded-[100%]"
        />
      </div>
      <div className="md:pt-[10px] pl-[15px] w-[250%]">
        <label className="italic text-[22px] font-bold">
          {name} ({startYear}-{endYear ?? "present"})
        </label>
        <br />
        <br />
        <label className="w-[250%] text-[18px]">{description}</label>
        <br />
        <br />
        {website && <Website name="Visit website..." link={website} />}
        &nbsp;
        {sourceCode && <Website name="View source code..." link={sourceCode} />}
      </div>
    </div>
  );
};

export default Project;
