// components/Name/index.tsx
import * as React from "react";

const Name = (): React.ReactElement => {
  return (
    <div className="bg-[#673AB7] h-[125px] md:h-[175px] font-[SFUI] text-[30px] md:text-[55px] font-black text-gray-50 md:pl-[40px]">
      <div className="relative top-[50%] translate-y-[-50%] md:w-[400px] w-[200px] left-[50%] translate-x-[-50%]">
        Baraa Al-Masri
      </div>
    </div>
  );
};

export default Name;

// client/src/lib/components/Name.svelte
<div
    class="relative bg-[#673AB7] h-[125px] md:h-[175px] font-[SFUI] text-[30px] md:text-[55px] font-black text-gray-50 md:pl-[40px]"
>
    <span
        class="absolute top-[50%] translate-y-[-50%] md:w-[400px] w-[200px] left-[50%] translate-x-[-50%]"
    >
        Baraa Al-Masri
    </span>
</div>
